# Ansible Inventory for La Chatte à Dédé

all:
  hosts:
    vps:
      ansible_host: 179.237.99.47
      ansible_user: debian
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: ~/.ssh/id_rsa_vps

  children:
    production:
      hosts:
        vps:
